#!/usr/bin/env ruby
ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../../Gemfile", __FILE__)

require "bundler/setup"
require "sequel"
require "sqlite3"

unless ARGV[0]
  puts "usage: #{__FILE__} <PATH>"
  puts "       #{__FILE__} ~/Desktop/transmitters.sqlite"
  abort
end

DB = Sequel.connect "sqlite://#{File.expand_path(ARGV[0])}"
DB.create_table! :transmitters do
  primary_key :id
  String :licence_id
  String :licence_no
  String :licence_type
  String :licensee
  String :channel
  String :frequency
  String :location
  String :grid_reference
  String :status
  String :power
  String :polarisation
end
