#!/usr/bin/env ruby
ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../../Gemfile", __FILE__)

require "bundler/setup"
require "sequel"
require "sqlite3"

unless ARGV[0]
  puts "usage: #{__FILE__} <PATH>"
  puts "       #{__FILE__} ~/Desktop/locations.sqlite"
  abort
end

DB = Sequel.connect "sqlite://#{File.expand_path(ARGV[0])}"
DB.create_table! :locations do
  primary_key :id
  String :topo50_grid_reference
  String :wgs84_latitude
  String :wgs84_longitude
end
